### PR TITLE
Update package.json

### PR DESCRIPTION
**Pull request by AlooAkbar**

### CODE REVIEW

**Comment by AlooAkbar** [comment]
closes #5 . https://github.com/matheuss/google-translate-api is broken, and the fix from https://github.com/vitalets/google-translate-api does not work anymore.

I forked https://github.com/matheuss/google-translate-api and simply changed index.js line 35 to `client: 'gtx',` instead of `client: 't',` ask suggested [here](https://github.com/matheuss/google-translate-api/issues/79). I don't know why, but that seems to be the correct fix.

**Comment by NotMyself** [comment]
Any reason you are not submitting this to the original package as a PR?

**Comment by AlooAkbar** [comment]
Hmmm, good point. Just submitted it. I didn't earlier because I assumed someone else commenting on the issue had already made a pull request with the same fix. I think I see why no one bothered though -  the package does not look actively maintained. There may be no way to actually merge it.

I'll try contacting the maintainer, but in the meantime this may still be the best solution.

**Comment by NotMyself** [comment]
OK I am going to pull it in with the caviate that if the original packages accept we can go back.

**Pull request merged**
